dz_practical/urls.py
from django.urls import path

from . import views


urlpatterns = [
    path('new_post/', views.post_new, name='new_post'),
    path('<int:pk>/update/', views.UserPostUpdate.as_view(), name='update'),
    path('create_comment/<int:pk>/', views.create_comments, name='create_comments'),
    path('', views.PostList.as_view(), name='post'),
    path('author_post/<int:pk>/', views.author_post, name='author_post'),
    path('post_detail/<int:pk>/', views.detail_post, name='post_detail'),
    path('my_blanks/', views.MyBlanks.as_view(), name='my_blanks'),
    path('contact_form/', views.contact_form, name='contact_form')

]

practical/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path('admin/', admin.site.urls),
    path('dz_practical/', include('dz_practical.urls')),
    path('accounts/', include('register.urls')),
    path('userprofile/', include('userprofile.urls')),

]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
        path('__debug__/', include(debug_toolbar.urls)),
    ]

register/urls.py
from django.contrib.auth import views as viewss
from django.urls import path, reverse_lazy

from . import views

app_name = 'accounts'

urlpatterns = [
    path("login/", viewss.LoginView.as_view(next_page='/dz_practical/'), name="login"),
    path("logout/", viewss.LogoutView.as_view(), name="logout"),

    path("password_change/", viewss.PasswordChangeView.as_view(), name="password_change"),
    path("password_change/done/", viewss.PasswordChangeDoneView.as_view(), name="password_change_done"),

    path("password_reset/", viewss.PasswordResetView.as_view(success_url=reverse_lazy('accounts:password_reset_done')),
         name="password_reset"),
    path("password_reset/done/", viewss.PasswordResetDoneView.as_view(), name="password_reset_done"),

    path("reset/<uidb64>/<token>/", viewss.PasswordResetConfirmView.as_view(), name="password_reset_confirm"),
    path("reset/done/", viewss.PasswordResetCompleteView.as_view(), name="password_reset_complete"),
    path("registration/", views.registers, name='registration')
]

userprofile/urls.py
from django.urls import path

from . import views

app_name = 'userprofile'
urlpatterns = [
    path('authorprofile/<int:pk>/', views.public_profile, name='public_profile'),
    path('my_profile/', views.my_profile, name='my_profile'),
    path('update_profile/', views.UpdateProfile.as_view(), name='update_profile')

dz_practical/models.py
from django.contrib.auth import get_user_model
from django.core.mail import send_mail
from django.db import models
from django.urls import reverse

from django_lifecycle import AFTER_UPDATE, LifecycleModel, hook

User = get_user_model()


class Posts(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=80)
    text = models.TextField()
    create_date = models.DateTimeField()
    published_date = models.DateTimeField()
    is_publish = models.BooleanField(default=False)

    def __str__(self):
        return self.title


class Comments(LifecycleModel):
    name = models.CharField(max_length=50, null=True)
    text = models.TextField()
    published_date = models.DateTimeField()
    is_publish = models.BooleanField(default=False)
    post = models.ForeignKey(Posts, on_delete=models.CASCADE)

    @hook(AFTER_UPDATE, when="is_publish", was=False, is_now=True)
    def on_publish(self):
        send_mail('You have a new Comment', ' http://127.0.0.1:8000' +
                  reverse('post_detail', args=[str(self.post.id)]), 'company@gmail.com', [self.post.author.email],
                  fail_silently=False)

    def __str__(self):
        return self.text

dz_practical/forms.py
from django import forms
from django.contrib.auth import get_user_model

from .models import Comments, Posts

User = get_user_model()


class PostsForm(forms.ModelForm):
    class Meta:
        model = Posts
        fields = ('title', 'text', 'is_publish')


class CommentsForm(forms.ModelForm):
    class Meta:
        model = Comments
        fields = ('name', 'text',)


class Mail(forms.Form):
    mail = forms.EmailField(label='You email')
    text = forms.CharField(widget=forms.Textarea(attrs={"rows": "10"}))

dz_practical/views.py
from django.contrib import messages
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.mail import send_mail
from django.core.paginator import Paginator
from django.db.models import Count, Q
from django.http import JsonResponse
from django.shortcuts import get_object_or_404, redirect, render
from django.template.loader import render_to_string
from django.urls import reverse
from django.utils import timezone
from django.views import generic

from .forms import CommentsForm, Mail, PostsForm
from .models import Posts

User = get_user_model()


@login_required(login_url='/register/login/')
def post_new(request):
    if request.method == 'POST':
        form = PostsForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.create_date = timezone.now()
            post.published_date = timezone.now()
            post.save()
            text = form.cleaned_data['text']
            send_mail('You have a new comment', text, 'company@gmail.com', ['admin@gmail.com'])
            messages.add_message(request, messages.SUCCESS, 'Post create')
            return redirect('post_detail', pk=post.id)
    else:
        form = PostsForm()
    return render(request, 'dz_practical/new_post.html', {'form': form})


class UserPostUpdate(LoginRequiredMixin, generic.UpdateView):
    model = Posts
    fields = ['title', 'text', 'is_publish']
    template_name = 'dz_practical/update_post.html'
    context_object_name = 'posts'

    def get_queryset(self):
        posts = Posts.objects.filter(author=self.request.user)
        return posts

    def get_success_url(self):
        return reverse('post_detail', kwargs={'pk': self.object.id})


def create_comments(request, pk):
    if request.method == 'POST':
        form = CommentsForm(request.POST)
        if form.is_valid():
            comm = form.save(commit=False)
            comm.published_date = timezone.now()
            comm.post_id = pk
            comm.save()

            send_mail('You have a new Post', form.cleaned_data['text'], 'company@gmail.com', ['admin@gmail.com'])
            messages.add_message(request, messages.SUCCESS, 'Comment create')
            return redirect('post_detail', pk=pk)
    else:
        form = CommentsForm()
    return render(request, 'dz_practical/create_comments.html', {'form': form, 'pk': pk})


class PostList(generic.ListView):
    model = Posts
    paginate_by = 5
    template_name = 'dz_practical/post_list.html'
    context_object_name = 'posts'

    def get_queryset(self):
        cont = Count('comments', filter=Q(comments__is_publish=True))
        posts = Posts.objects.select_related('author').filter(is_publish=True).annotate(cont=cont)
        return posts


def author_post(request, pk):
    author = get_object_or_404(User, pk=pk)
    page_obj = author.posts_set.filter(is_publish=True).annotate(cont=Count('comments',
                                                                            filter=Q(comments__is_publish=True)))
    paginator = Paginator(page_obj, 5)
    page_obj = request.GET.get('page')
    page_obj = paginator.get_page(page_obj)
    return render(request, 'dz_practical/author_post.html', {'page_obj': page_obj, 'author': author})


def detail_post(request, pk):
    post = get_object_or_404(Posts, pk=pk)
    comm = post.comments_set.filter(is_publish=True)
    paginator = Paginator(comm, 5)
    page_number = request.GET.get('page')
    comm = paginator.get_page(page_number)
    return render(request, 'dz_practical/post_detail.html', {'post': post, 'comm': comm})


class MyBlanks(LoginRequiredMixin, generic.ListView):
    model = Posts
    template_name = 'dz_practical/my_blanks.html'
    context_object_name = 'posts'
    paginate_by = 5

    def get_queryset(self):
        posts = Posts.objects.filter(author=self.request.user, is_publish=False)
        return posts

    def get_success_url(self):
        return reverse('post_detail', kwargs={'pk': self.object.id})


def contact_form(request):
    data = dict()
    if request.method == "POST":
        form = Mail(request.POST)
        if form.is_valid():
            data['form_is_valid'] = True
            client_email = form.cleaned_data['mail']
            text = form.cleaned_data['text']
            text = text + f'\nClient email: {client_email}'
            subject = 'Someone need your help'
            send_mail(subject, text, 'company@gmail.com', ['admin@gmail.com'])

        else:
            data['form_is_valid'] = False
    else:
        form = Mail()
    context = {'form': form}
    data['html_form'] = render_to_string('dz_practical/contact_form.html', context, request=request)
    return JsonResponse(data)

templates/dz_practical/author_post.html
{% extends "base.html" %}
{% block title %}Profile{% endblock %}
{% block content %}
 {% if page_obj %}
    <p><h4>Author:<a href="{% url 'userprofile:public_profile' author.id %}">{{author.username}}</a></h4></p>
     {% for i in page_obj %}
        <ul>
        <p><a href="{% url 'post_detail' i.id %}">{{i.title}}</a></p>
        <p>{{i.text}}</p>
            <p> Publish date: {{i.published_date}} </p>
            <p>Has {{i.cont}} comments</p>
        </ul>
        <hr>
     {% endfor %}
 {% else %}
    <p>Has not post</p>
 {% endif %}

{% endblock %}

templates/dz_practical/contact_form.html
{% load widget_tweaks %}
{% block content %}

<form method="post" action="{% url 'contact_form' %}" class="js-contact-us-form">
  {% csrf_token %}
    <div class="modal-header">
        <h4 class="modal-title">Contact us</h4>
        <button type="button" class="close" data-bs-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
        </button>
    </div>
    <div class="modal-body">
     {% for field in form %}
      <div class="form-group{% if field.errors %} has-error{% endif %}">
        <label >{{ field.label }}</label>
        {% if form.is_bound %}
          {% if field.errors %}
            {% render_field field class+="form-control is-invalid" %}
            {% for error in field.errors %}
              <div class="invalid-feedback">
                {{ error }}
              </div>
            {% endfor %}
          {% else %}
            {% render_field field class+="form-control is-valid" %}
          {% endif %}
        {% else %}
          {% render_field field class+="form-control" %}
        {% endif %}
      </div>
    {% endfor %}
    </div>
    <div class="modal-footer">
    <button type="button" class="btn btn-default" data-bs-dismiss="modal">Close</button>
    <button type="submit" class="btn btn-primary">Contact us</button>
    </div>
</form>
{% endblock %}

templates/dz_practical/create_comments.html
{% extends "base.html" %}
{% block title %}Create comments{% endblock %}
{% block content %}
<h4>Create comments</h4>
<form action="{% url 'create_comments' pk %}" method="POST">
  {% csrf_token %}
  {{form.as_p}}
    <input type="submit" value="Comment">
{% endblock %}

templates/dz_practical/my_blanks.html
{% extends "base.html" %}
{% block title %}ALL POST{% endblock %}
{% block content %}
 {% if posts %}
<h1>ALL POST</h1>
     {% for i in posts %}
        <h3><p><a href="{% url 'post_detail' i.id%}">{{i.title}}</a></p></h3>
        <p>Author:&nbsp;<a href="{% url 'userprofile:public_profile' i.author.id%}">{{ i.author }}</a> </p>
        <p><a href="{% url 'author_post' i.author.id%}">Show all post</a></p>
        <p>Publish date: {{i.published_date}}</p>
        <p>Create date: {{i.create_date}}</p>
        {% if i.cont %}
        <p>Have {{i.cont}} comments</p>
        {% endif %}
        <p><a href="{% url 'update' i.id%}">Update</a> </p>
        <hr>
     {% endfor %}
 {% else %}
    <p>Has not post</p>
 {% endif %}

{% endblock %}

templates/dz_practical/new_post.html
{% extends "base.html" %}
{% block title %}Create post{% endblock %}
{% block content %}
<h4>Create post </h4>
<form action="{% url 'new_post' %}" method="POST">
  {% csrf_token %}
     {{form.as_p}}
    <p><input type="submit" value="create"></p>
</form>
{% endblock %}

templates/dz_practical/post_detail.html
{% extends "base.html" %}
{% block title %}Post detail{% endblock %}
{% block content %}
 {% if post %}
<div class="container-fluid">
  <div class="row">
    <div class="col-sm-2">
    <img src="https://cdn-icons-png.flaticon.com/512/25/25231.png" width="150" height="150">
   </div>
  </div>
</div>
<p><h3>{{post.title}}</p></h3>
    <p>{{post.text}}</p>
    <p>Author:&nbsp;<a href="{% url 'author_post' post.author.id%}">{{ post.author }}</a></p>
    <p>Publish date: {{post.published_date}}</p>
        <hr>
        <a href="{% url 'create_comments' post.id %}">Create comment</a>
        <p><h4>Comments</h4></p>
            {% if comm %}
            {% for comm in comm %}
                <li>{{comm.name}}</li>
                <ul><p>{{comm.text}}</p></ul>
                <hr>
            {% endfor %}
        {% else %}
            <p> Has no comm</p>
        {% endif %}
 {% else %}
    <p>Has not post</p>
 {% endif %}
{% endblock %}
      {% block pagination %}
          <div class="pagination">
            <span class="page-links">
                {% if comm.has_previous %}
                  <a href="{{ request.path }}?page={{ comm.previous_page_number }}">Previous</a>
                {% endif %}
              <span class="page-current">
                    Page {{ comm.number }} of {{ comm.paginator.num_pages }}.
                </span>
              {% if comm.has_next %}
                <a href="{{ request.path }}?page={{ comm.next_page_number }}">Next</a>
              {% endif %}
            </span>
          </div>
      {% endblock %}

templates/dz_practical/post_list.html
{% extends "base.html" %}
{% block title %}ALL POST{% endblock %}
{% block content %}
 {% if posts %}
<h1>ALL POST</h1>
     {% for i in posts %}
        <h3><p>Post title: <a href="{% url 'post_detail' i.id%}">{{i.title}}</a></p></h3>
        <p>Author:&nbsp;<a href="{% url 'userprofile:public_profile' i.author.id%}">{{ i.author }}</a> </p>
        <p><a href="{% url 'author_post' i.author.id%}">Show all post</a></p>
        <p>Publish date: {{i.published_date}}</p>
        <p>Have {{i.cont}} comments</p>
        <p><a href="{% url 'create_comments' i.id%}">Create comments</a> </p>
        <hr>
     {% endfor %}
 {% else %}
    <p>Has not post</p>
 {% endif %}

{% endblock %}

templates/dz_practical/success_contact.html
{% block content %}
<form method="post" action="{% url 'contact_form' %}" class="js-contact-us-form">
  {% csrf_token %}
    <div class="modal-header">
        <h4 class="modal-title">Contact us</h4>
        <button type="button" class="close" data-bs-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
        </button>
    </div>
    <div class="modal-body">
     <h3>Contact is SUCCESS</h3>
    </div>
</form>
{% endblock %}

templates/dz_practical/update_post.html
{% extends "base.html" %}
{% block title %}Update Post{% endblock %}
{% block content %}
<form method="post">
    {% csrf_token %}
      {{ form.as_p }}
    <input type="submit" value="Update"/>
{% endblock %}