practical/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path('admin/', admin.site.urls),
    path('dz_practical/', include('dz_practical.urls')),
    path('accounts/', include('register.urls')),
    path('userprofile/', include('userprofile.urls')),

]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
        path('__debug__/', include(debug_toolbar.urls)),
    ]

register/urls.py
from django.contrib.auth import views as viewss
from django.urls import path, reverse_lazy

from . import views

app_name = 'accounts'

urlpatterns = [
    path("login/", viewss.LoginView.as_view(next_page='/dz_practical/'), name="login"),
    path("logout/", viewss.LogoutView.as_view(), name="logout"),

    path("password_change/", viewss.PasswordChangeView.as_view(), name="password_change"),
    path("password_change/done/", viewss.PasswordChangeDoneView.as_view(), name="password_change_done"),

    path("password_reset/", viewss.PasswordResetView.as_view(success_url=reverse_lazy('accounts:password_reset_done')),
         name="password_reset"),
    path("password_reset/done/", viewss.PasswordResetDoneView.as_view(), name="password_reset_done"),

    path("reset/<uidb64>/<token>/", viewss.PasswordResetConfirmView.as_view(), name="password_reset_confirm"),
    path("reset/done/", viewss.PasswordResetCompleteView.as_view(), name="password_reset_complete"),
    path("registration/", views.registers, name='registration')
]

userprofile/urls.py
from django.urls import path

from . import views

app_name = 'userprofile'
urlpatterns = [
    path('authorprofile/<int:pk>/', views.public_profile, name='public_profile'),
    path('my_profile/', views.my_profile, name='my_profile'),
    path('update_profile/', views.UpdateProfile.as_view(), name='update_profile')

userprofile/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.paginator import Paginator
from django.shortcuts import get_object_or_404, render
from django.urls import reverse_lazy
from django.views import generic

User = get_user_model()


def public_profile(request, pk):
    author = get_object_or_404(User, pk=pk)
    post = author.posts_set.filter(is_publish=True)
    return render(request, 'userprofile/author_profile.html', {'author': author, 'post': post})


@login_required
def my_profile(request):
    author = get_object_or_404(User, pk=request.user.id)
    page_obj = author.posts_set.filter(is_publish=True)
    paginator = Paginator(page_obj, 5)
    page_obj = request.GET.get('page')
    page_obj = paginator.get_page(page_obj)
    return render(request, 'userprofile/my_profile.html', {'author': author, 'page_obj': page_obj})


class UpdateProfile(LoginRequiredMixin, generic.UpdateView):
    model = User
    fields = ["username", "email"]
    template_name = 'userprofile/update_profile.html'
    success_url = reverse_lazy("userprofile:my_profile")
    success_message = "Profile updated"

    def get_object(self, queryset=None):
        user = self.request.user
        return user

templates/userprofile/author_profile.html
{% extends "base.html" %}
{% block title %}Profile{% endblock %}
{% block content %}
 {% if author %}
<p><h3>Username: {{author.username}}</p></h3>
    <p>Email: {{author.email}}</p>
        <hr>
        {% if post %}
        <p><a href="{% url 'author_post' author.id%}">Show all post</a></p>
        {% else %}
            <p>No posts</p>
        {% endif %}
 {% endif %}
{% endblock %}

templates/userprofile/my_profile.html
{% extends "base.html" %}
{% block title %}My profile{% endblock %}
{% block content %}
 {% if author %}
<p><h3>Username: {{author.username}}</p></h3>
    <p>Email: {{author.email}}</p>
    <ul>
    <p><a href="{% url 'accounts:password_change' %}">Password change</a></p>
    <p><a href="{% url 'userprofile:update_profile'%}">Update my profile</a></p>
    </ul>
        <hr>
        {% if page_obj %}
            {% for post in page_obj %}
                <p><h5>Post Title:</h5><h3><a href="{% url 'post_detail' post.id%}">{{post.title}}</a></h3></p>
                <p><h5>Post text:</h5> {{post.text}}</p>
                <p>Date published: {{post.published_date}}</p>
                <p><a href="{% url 'update' post.id%}">Update post</a> </p>
                <hr>

            {% endfor %}
        {% else %}
            <p> Has no post</p>
        {% endif %}

 {% else %}
    <p>Has not post</p>
 {% endif %}
{% endblock %}

templates/userprofile/update_profile.html
{% extends "base.html" %}
{% block title %}Update my profile{% endblock %}
{% block content %}

  <form method="POST" class="form-group">
    {% csrf_token %}
    <table>
      {{ form.as_table }}
    </table>
    <input type="submit" value="Update">
  </form>

{% endblock %}