practical/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path('admin/', admin.site.urls),
    path('dz_practical/', include('dz_practical.urls')),
    path('accounts/', include('register.urls')),
    path('userprofile/', include('userprofile.urls')),

]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
        path('__debug__/', include(debug_toolbar.urls)),
    ]

register/urls.py
from django.contrib.auth import views as viewss
from django.urls import path, reverse_lazy

from . import views

app_name = 'accounts'

urlpatterns = [
    path("login/", viewss.LoginView.as_view(next_page='/dz_practical/'), name="login"),
    path("logout/", viewss.LogoutView.as_view(), name="logout"),

    path("password_change/", viewss.PasswordChangeView.as_view(), name="password_change"),
    path("password_change/done/", viewss.PasswordChangeDoneView.as_view(), name="password_change_done"),

    path("password_reset/", viewss.PasswordResetView.as_view(success_url=reverse_lazy('accounts:password_reset_done')),
         name="password_reset"),
    path("password_reset/done/", viewss.PasswordResetDoneView.as_view(), name="password_reset_done"),

    path("reset/<uidb64>/<token>/", viewss.PasswordResetConfirmView.as_view(), name="password_reset_confirm"),
    path("reset/done/", viewss.PasswordResetCompleteView.as_view(), name="password_reset_complete"),
    path("registration/", views.registers, name='registration')
]

userprofile/urls.py
from django.urls import path

from . import views

app_name = 'userprofile'
urlpatterns = [
    path('authorprofile/<int:pk>/', views.public_profile, name='public_profile'),
    path('my_profile/', views.my_profile, name='my_profile'),
    path('update_profile/', views.UpdateProfile.as_view(), name='update_profile')

templates/base.html
{% load static %} <!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <script src="https://code.jquery.com/jquery-3.6.1.js" integrity="sha256-3zlB5s2uwoUzrXK3BT7AX3FyvojsraNFxCc2vC/7pNI=" crossorigin="anonymous"></script>
     <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"
             integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4"
             crossorigin="anonymous"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css"
          rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65"
          crossorigin="anonymous">
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
{% block extra_js %}
  <script src="{% static '/js/contact.js' %}"></script>
{% endblock %}
{% if messages %}
    <div class="row">
      <div class="col-sm-12">
        {% for message in messages %}
          <div class="alert alert-{{ message.tags }} alert-dismissible text-center" role="alert">
            <button type="button" class="close" data-bs-dismiss="alert" aria-label="Close"><span
                aria-hidden="true">&times;</span></button>
            <strong>{% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}Error{% else %}
              {{ message.tags|title }}{% endif %}!</strong> {{ message }}
          </div>
        {% endfor %}
      </div>
    </div>
  {% endif %}
<div class="container-fluid">
  <div class="row">
    <div class="col-sm-2">
        <div class="sidebar-nav">
            <p>Navigation</p>
          <li><a href="{% url 'post' %}">ALL post</a></li>
            <hr>
            <div class="sidebar-nav">
                {% if user.is_authenticated %}
                <li><a href="{% url 'new_post' %}">Create Post</a></li>
                <li><a href="{% url 'userprofile:my_profile' %}">My profile</a></li>
                <li><a href="{% url 'accounts:logout' %}">logout</a></li>
                <li><a href="{% url 'my_blanks' %}">Show my blanks</a></li>

                {%else%}
                <li><a href="{% url 'accounts:login' %}">Login</a></li>
                <li><a href="{% url 'accounts:registration' %}?next={{ request.path }}">Registration</a></li>
                {% endif %}
                <hr>
                <p>
                <button type="button" class="btn btn-primary js-create-book" data-url="{% url 'contact_form' %}">
                <span class="glyphicon glyphicon-plus"></span>
                    Contact us
                </button>
                </p>
            </div>
        </div>
    </div>
      <div class="col-sm-10 ">
          {% block content %}{% endblock %}
        {% block pagination %}
          {% if page_obj %}
          <div class="pagination">
            <span class="page-links">
                {% if page_obj.has_previous %}
                  <a href="{{ request.path }}?page={{ page_obj.previous_page_number }}">Previous</a>
                {% endif %}
              <span class="page-current">
                    Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                </span>
              {% if page_obj.has_next %}
                <a href="{{ request.path }}?page={{ page_obj.next_page_number }}">Next</a>
              {% endif %}
            </span>
          </div>
          {% endif %}
      {% endblock %}
      </div>
  </div>
</div>
<div class="modal fade" id="modal-contact" tabindex="-1">
            <div class="modal-dialog">
                <div class="modal-content">

                </div>
            </div>
</div>
<div class="modal fade" id="modal-message" tabindex="-1">
            <div class="modal-dialog">
                <div class="modal-content">
                <div class="modal-header">
            <h5 class="modal-title">Messages</h5>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
          </div>
          <div class="modal-body">
            <p>Your message has been sent to an administrator!</p>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

</body>
</html>